"""Natural-language parsing boundaries for typed optimizer inputs."""

from .dayplan import (
    DAYPLAN_EXTRACTION_INSTRUCTIONS,
    DayPlanAPIError,
    DayPlanError,
    DayPlanExtraction,
    DayPlanInputError,
    DayPlanOutputError,
    DayPlanRefusalError,
    MissingAPIKeyError,
    TextSolveResult,
    parse_dayplan,
    solve_from_text,
)
from .shift_schedule import (
    SHIFTSCHEDULE_EXTRACTION_INSTRUCTIONS,
    ShiftScheduleAPIError,
    ShiftScheduleError,
    ShiftScheduleExtraction,
    ShiftScheduleInputError,
    ShiftScheduleMissingAPIKeyError,
    ShiftScheduleOutputError,
    ShiftScheduleRefusalError,
    ShiftScheduleTextSolveResult,
    parse_shift_schedule,
    solve_from_text as solve_shift_schedule_from_text,
)

__all__ = [
    "DAYPLAN_EXTRACTION_INSTRUCTIONS",
    "DayPlanAPIError",
    "DayPlanError",
    "DayPlanExtraction",
    "DayPlanInputError",
    "DayPlanOutputError",
    "DayPlanRefusalError",
    "MissingAPIKeyError",
    "TextSolveResult",
    "parse_dayplan",
    "solve_from_text",
    "SHIFTSCHEDULE_EXTRACTION_INSTRUCTIONS",
    "ShiftScheduleAPIError",
    "ShiftScheduleError",
    "ShiftScheduleExtraction",
    "ShiftScheduleInputError",
    "ShiftScheduleMissingAPIKeyError",
    "ShiftScheduleOutputError",
    "ShiftScheduleRefusalError",
    "ShiftScheduleTextSolveResult",
    "parse_shift_schedule",
    "solve_shift_schedule_from_text",
]
